import { WordDBType } from "@/types/globaltype";

export const dummyWords: Array<WordDBType> = [
    {
        id: 16,
        english: "committee",
        japanese: "委員会",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 16,
        user_id: 1
    },
    {
        id: 17,
        english: "indeed",
        japanese: "本当に",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 17,
        user_id: 1
    },
    {
        id: 18,
        english: "authority",
        japanese: "権威、権限",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 18,
        user_id: 1
    },
    {
        id: 19,
        english: "union",
        japanese: "労働組合",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 19,
        user_id: 1
    },
    {
        id: 20,
        english: "issue",
        japanese: "問題",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 20,
        user_id: 1
    },
    {
        id: 21,
        english: "increase",
        japanese: "増える",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 21,
        user_id: 1
    },
    {
        id: 22,
        english: "lord",
        japanese: "貴族",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 22,
        user_id: 1
    },
    {
        id: 23,
        english: "various",
        japanese: "さまざまな",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 23,
        user_id: 1
    },
    {
        id: 24,
        english: "basis",
        japanese: "基礎",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 24,
        user_id: 1
    },
    {
        id: 25,
        english: "despite",
        japanese: "〜にもかかわらず",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 25,
        user_id: 1
    },
    {
        id: 41,
        english: "consider",
        japanese: "を〜と見なす、を熟考する",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 41,
        user_id: 1
    },
    {
        id: 42,
        english: "attempt",
        japanese: "を試みる",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 42,
        user_id: 1
    },
    {
        id: 43,
        english: "specific",
        japanese: "特定の、明確な",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 43,
        user_id: 1
    },
    {
        id: 44,
        english: "leading",
        japanese: "主要な",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 44,
        user_id: 1
    },
    {
        id: 45,
        english: "potential",
        japanese: "潜在力、可能性",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 45,
        user_id: 1
    },
    {
        id: 46,
        english: "access",
        japanese: "接近、進入路",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 46,
        user_id: 1
    },
    {
        id: 47,
        english: "independent",
        japanese: "独立した",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 47,
        user_id: 1
    },
    {
        id: 48,
        english: "benefit",
        japanese: "恩恵、利益",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 48,
        user_id: 1
    },
    {
        id: 49,
        english: "employment",
        japanese: "職、雇用",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 49,
        user_id: 1
    },
    {
        id: 50,
        english: "influence",
        japanese: "影響、効果",
        created_at: new Date('2023-08-29 07:06:21.857'),
        deleted_at: null,
        last_time_at: new Date('2023-09-06 08:41:01.953'),
        complete: false,
        today_learning: true,
        user_answer: "",
        right_or_wrong: false,
        correct_count: 4,
        question_count: 4,
        correct_rate: 100,
        user_word_id: 50,
        user_id: 1
    },
];