import { WordDataType } from "@/types/globaltype";

export const wordList: WordDataType[] = [
    {
        id: 1,
        english: 'being',
        japanese: '存在',
        date: '2023/07/28',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 2,
        english: 'government',
        japanese: '政府',
        date: '2023/07/28',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 3,
        english: 'found',
        japanese: '設立する',
        date: '2023/07/28',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 4,
        english: 'given',
        japanese: '〜を仮定すれば',
        date: '2023/07/28',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 5,
        english: 'state',
        japanese: 'を述べる',
        date: '2023/07/28',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 6,
        english: 'council',
        japanese: '地方議会',
        date: '2023/07/28',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 7,
        english: 'available',
        japanese: '入手できる',
        date: '2023/07/28',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 8,
        english: 'saw',
        japanese: 'のこぎり',
        date: '2023/07/28',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 9,
        english: 'minister',
        japanese: '大臣',
        date: '2023/07/28',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 10,
        english: 'means',
        japanese: '手段',
        date: '2023/07/28',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 11,
        english: 'therefore',
        japanese: 'それゆえに',
        date: '2023/07/28',
        editing: false,
        register: "出題",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 12,
        english: 'evidence',
        japanese: '証拠',
        date: '2023/07/28',
        editing: false,
        register: "出題",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 13,
        english: 'range',
        japanese: '範囲',
        date: '2023/07/28',
        editing: false,
        register: "出題",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 14,
        english: 'thus',
        japanese: 'このように',
        date: '2023/07/28',
        editing: false,
        register: "出題",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 15,
        english: 'individual',
        japanese: '個々の',
        date: '2023/07/28',
        editing: false,
        register: "出題",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 16,
        english: 'committee',
        japanese: '委員会',
        date: '2023/07/28',
        editing: false,
        register: "出題",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 17,
        english: 'indeed',
        japanese: '本当に',
        date: '2023/08/11',
        editing: false,
        register: "出題",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 18,
        english: 'authority',
        japanese: '権威、権限',
        date: '2023/08/11',
        editing: false,
        register: "出題",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 19,
        english: 'union',
        japanese: '労働組合',
        date: '2023/08/11',
        editing: false,
        register: "出題",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 20,
        english: 'increase',
        japanese: '増える',
        date: '2023/08/11',
        editing: false,
        register: "出題",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 21,
        english: 'issue',
        japanese: '問題',
        date: '2023/08/11',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 22,
        english: 'lord',
        japanese: '貴族',
        date: '2023/08/11',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 23,
        english: 'various',
        japanese: 'さまざまな',
        date: '2023/08/11',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 24,
        english: 'basis',
        japanese: '基礎',
        date: '2023/08/11',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    },
    {
        id: 25,
        english: 'despite',
        japanese: '〜にもかかわらず',
        date: '2023/08/11',
        editing: false,
        register: "出題しない",
        complete: false,
        yourAnswer: "",
        rightWrong: false,
        correctAnswer: 0,
        questionNum: 0,
        correctRate: 0
    }
];
